library(readtext)
library(dplyr)
library(tidyr)
library(stringr)

activity_labels <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/activity_labels.txt")
features <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/features.txt")

subject_train <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/train/subject_train.txt")
X_train <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/train/X_train.txt")
y_train <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/train/y_train.txt")
body_acc_x_train <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/train/Inertial Signals/body_acc_x_train.txt")
body_acc_y_train <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/train/Inertial Signals/body_acc_y_train.txt")
body_acc_z_train <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/train/Inertial Signals/body_acc_z_train.txt")
body_gyro_x_train <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/train/Inertial Signals/body_gyro_x_train.txt")
body_gyro_y_train <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/train/Inertial Signals/body_gyro_y_train.txt")
body_gyro_z_train <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/train/Inertial Signals/body_gyro_z_train.txt")
total_acc_x_train <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/train/Inertial Signals/total_acc_x_train.txt")
total_acc_y_train <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/train/Inertial Signals/total_acc_y_train.txt")
total_acc_z_train <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/train/Inertial Signals/total_acc_z_train.txt")

subject_test <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/test/subject_test.txt")
X_test <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/test/X_test.txt")
y_test <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/test/y_test.txt")
body_acc_x_test <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/test/Inertial Signals/body_acc_x_test.txt")
body_acc_y_test <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/test/Inertial Signals/body_acc_y_test.txt")
body_acc_z_test <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/test/Inertial Signals/body_acc_z_test.txt")
body_gyro_x_test <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/test/Inertial Signals/body_gyro_x_test.txt")
body_gyro_y_test <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/test/Inertial Signals/body_gyro_y_test.txt")
body_gyro_z_test <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/test/Inertial Signals/body_gyro_z_test.txt")
total_acc_x_test <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/test/Inertial Signals/total_acc_x_test.txt")
total_acc_y_test <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/test/Inertial Signals/total_acc_y_test.txt")
total_acc_z_test <- readtext("Documents/Springboard Files/Data Wrangling/Samsung Galaxy/UCI HAR Dataset/test/Inertial Signals/total_acc_z_test.txt")


features <- as.character(features["text"])
features <- str_split(features, "\n")
features <- as.data.frame(features, stringsAsFactors = FALSE, col.names = c("Feature Name"))
features <- features %>% separate(Feature.Name, c("Number", "Name"), sep = " ")
features <- features[, "Name"]
